begin;

insert into public.beautydna_taxonomy_terms
  (taxonomy_key, term_code, label_en, sort_order)
values
('evidence_level', 'A', 'Regulatory or high-confidence clinical evidence', 1),
('evidence_level', 'B', 'Moderate human evidence', 2),
('evidence_level', 'C', 'Limited but relevant evidence', 3),
('evidence_level', 'D', 'Preliminary or indirect evidence', 4),
('evidence_level', 'E', 'Unsupported or marketing-level information', 5),
('fit_classification', 'strong_fit', 'Strong fit', 1),
('fit_classification', 'likely_fit', 'Likely fit', 2),
('fit_classification', 'conditional_fit', 'Conditional fit', 3),
('fit_classification', 'neutral', 'Neutral', 4),
('fit_classification', 'use_with_caution', 'Use with caution', 5),
('fit_classification', 'usually_unsuitable', 'Usually unsuitable', 6),
('fit_classification', 'insufficient_evidence', 'Insufficient evidence', 7),
('interaction_type', 'synergy', 'Synergy', 1),
('interaction_type', 'complementary', 'Complementary', 2),
('interaction_type', 'compatible', 'Compatible', 3),
('interaction_type', 'conditional_compatibility', 'Conditional compatibility', 4),
('interaction_type', 'redundant_action', 'Redundant action', 5),
('interaction_type', 'cumulative_irritation', 'Cumulative irritation', 6),
('interaction_type', 'ph_or_environment_dependency', 'pH or environment dependency', 7),
('interaction_type', 'chemical_stability_conflict', 'Chemical stability conflict', 8),
('interaction_type', 'formulation_incompatibility', 'Formulation incompatibility', 9),
('interaction_type', 'delivery_interference', 'Delivery interference', 10),
('interaction_type', 'sequencing_dependency', 'Sequencing dependency', 11),
('interaction_type', 'photosensitivity_burden', 'Photosensitivity burden', 12),
('interaction_type', 'allergy_cross_reactivity', 'Allergy cross-reactivity', 13),
('interaction_type', 'medical_caution', 'Medical caution', 14),
('interaction_type', 'insufficient_evidence', 'Insufficient evidence', 15),
('interaction_type', 'no_known_meaningful_interaction', 'No known meaningful interaction', 16),
('recommendation_action', 'can_be_used_together', 'Can be used together', 1),
('recommendation_action', 'prefer_same_routine', 'Prefer same routine', 2),
('recommendation_action', 'prefer_separate_layers', 'Prefer separate layers', 3),
('recommendation_action', 'allow_product_to_dry', 'Allow product to dry first', 4),
('recommendation_action', 'separate_am_pm', 'Use morning and evening separately', 5),
('recommendation_action', 'alternate_days', 'Alternate days', 6),
('recommendation_action', 'reduce_frequency', 'Reduce frequency', 7),
('recommendation_action', 'introduce_one_at_a_time', 'Introduce one product at a time', 8),
('recommendation_action', 'tolerant_skin_only', 'Use only if skin is tolerant', 9),
('recommendation_action', 'avoid_impaired_barrier', 'Avoid on impaired barrier', 10),
('recommendation_action', 'avoid_eye_area', 'Avoid around eyes', 11),
('recommendation_action', 'avoid_same_formulation', 'Avoid in the same formulation', 12),
('recommendation_action', 'avoid_defined_medical_condition', 'Avoid under specified medical condition', 13),
('recommendation_action', 'no_actionable_interaction', 'No actionable interaction established', 14),
('recommendation_action', 'insufficient_evidence', 'Insufficient evidence for a rule', 15),
('eligibility_status', 'blocked', 'Blocked', 1),
('eligibility_status', 'not_recommended', 'Not recommended', 2),
('eligibility_status', 'conditional', 'Conditional', 3),
('eligibility_status', 'eligible', 'Eligible', 4),
('eligibility_status', 'strong_match', 'Strong match', 5),
('eligibility_status', 'insufficient_data', 'Insufficient data', 6),
('review_status', 'needs_review', 'Needs review', 1),
('review_status', 'in_review', 'In review', 2),
('review_status', 'approved', 'Approved', 3),
('review_status', 'rejected', 'Rejected', 4),
('review_status', 'superseded', 'Superseded', 5),
('jurisdiction', 'JP', 'Japan', 1),
('jurisdiction', 'BR', 'Brazil', 2),
('jurisdiction', 'EU', 'European Union', 3),
('jurisdiction', 'US', 'United States', 4),
('environment_factor', 'temperature', 'Temperature', 1),
('environment_factor', 'relative_humidity', 'Relative humidity', 2),
('environment_factor', 'uv_index', 'UV index', 3),
('environment_factor', 'pollution', 'Pollution', 4),
('environment_factor', 'wind', 'Wind', 5),
('environment_factor', 'altitude', 'Altitude', 6),
('environment_factor', 'indoor_heating', 'Indoor heating', 7),
('environment_factor', 'air_conditioning', 'Air conditioning', 8),
('environment_factor', 'seasonal_change', 'Seasonal change', 9),
('environment_factor', 'saltwater_exposure', 'Ocean or saltwater exposure', 10),
('environment_factor', 'chlorinated_water', 'Chlorinated-water exposure', 11),
('environment_factor', 'hard_water', 'Hard-water exposure', 12),
('environment_factor', 'sweating', 'Sweating', 13),
('environment_factor', 'mask_wearing', 'Mask wearing', 14),
('environment_factor', 'occupational_exposure', 'Occupational exposure', 15),
('skin_concern', 'dehydration', 'Dehydration', 1),
('skin_concern', 'dryness', 'Dryness', 2),
('skin_concern', 'barrier_impairment', 'Barrier impairment', 3),
('skin_concern', 'excess_sebum', 'Excess sebum', 4),
('skin_concern', 'clogged_pore_tendency', 'Clogged-pore tendency', 5),
('skin_concern', 'active_blemishes', 'Active blemishes', 6),
('skin_concern', 'post_blemish_marks', 'Post-blemish marks', 7),
('skin_concern', 'uneven_tone', 'Uneven tone', 8),
('skin_concern', 'hyperpigmentation', 'Hyperpigmentation', 9),
('skin_concern', 'dullness', 'Dullness', 10),
('skin_concern', 'fine_lines', 'Fine lines', 11),
('skin_concern', 'loss_of_firmness', 'Loss of firmness', 12),
('skin_concern', 'rough_texture', 'Rough texture', 13),
('skin_concern', 'visible_pores', 'Visible pores', 14),
('skin_concern', 'redness', 'Redness', 15),
('skin_concern', 'sensitivity', 'Sensitivity', 16),
('skin_concern', 'irritation', 'Irritation', 17),
('skin_concern', 'flaking', 'Flaking', 18),
('skin_concern', 'sun_damage', 'Sun damage', 19),
('skin_concern', 'under_eye_dryness', 'Under-eye dryness', 20),
('skin_concern', 'lip_dryness', 'Lip dryness', 21),
('scalp_concern', 'oily_scalp', 'Oily scalp', 1),
('scalp_concern', 'dry_scalp', 'Dry scalp', 2),
('scalp_concern', 'sensitive_scalp', 'Sensitive scalp', 3),
('scalp_concern', 'flaking', 'Flaking', 4),
('scalp_concern', 'dandruff_tendency', 'Dandruff tendency', 5),
('scalp_concern', 'product_buildup', 'Product buildup', 6),
('scalp_concern', 'scalp_odor', 'Scalp odor', 7),
('scalp_concern', 'itching', 'Itching', 8),
('scalp_concern', 'root_breakage', 'Breakage near the root', 9),
('scalp_concern', 'chemically_treated_scalp_sensitivity', 'Chemically treated scalp sensitivity', 10),
('hair_concern', 'dryness', 'Dryness', 1),
('hair_concern', 'high_porosity', 'High porosity', 2),
('hair_concern', 'low_porosity', 'Low porosity', 3),
('hair_concern', 'breakage', 'Breakage', 4),
('hair_concern', 'frizz', 'Frizz', 5),
('hair_concern', 'tangling', 'Tangling', 6),
('hair_concern', 'loss_of_shine', 'Loss of shine', 7),
('hair_concern', 'heat_damage', 'Heat damage', 8),
('hair_concern', 'uv_damage', 'UV damage', 9),
('hair_concern', 'bleach_damage', 'Bleach damage', 10),
('hair_concern', 'color_fading', 'Color fading', 11),
('hair_concern', 'lack_of_volume', 'Lack of volume', 12),
('hair_concern', 'excess_weight', 'Excess weight', 13),
('hair_concern', 'curl_definition', 'Curl-definition needs', 14),
('function', 'humectant', 'Humectant', 1),
('function', 'emollient', 'Emollient', 2),
('function', 'occlusive', 'Occlusive', 3),
('function', 'surfactant', 'Surfactant', 4),
('function', 'cleansing_agent', 'Cleansing agent', 5),
('function', 'solvent', 'Solvent', 6),
('function', 'emulsifier', 'Emulsifier', 7),
('function', 'emulsion_stabilizer', 'Emulsion stabilizer', 8),
('function', 'thickener', 'Thickener', 9),
('function', 'film_former', 'Film former', 10),
('function', 'conditioning_agent', 'Conditioning agent', 11),
('function', 'antistatic_agent', 'Antistatic agent', 12),
('function', 'chelating_agent', 'Chelating agent', 13),
('function', 'buffer', 'Buffer', 14),
('function', 'ph_adjuster', 'pH adjuster', 15),
('function', 'preservative', 'Preservative', 16),
('function', 'preservative_booster', 'Preservative booster', 17),
('function', 'antioxidant', 'Antioxidant', 18),
('function', 'colorant', 'Colorant', 19),
('function', 'fragrance', 'Fragrance', 20),
('function', 'fragrance_masking_agent', 'Fragrance masking agent', 21),
('function', 'uv_filter', 'UV filter', 22),
('function', 'opacifying_agent', 'Opacifying agent', 23),
('function', 'absorbent', 'Absorbent', 24),
('function', 'abrasive', 'Abrasive', 25),
('function', 'keratolytic', 'Keratolytic', 26),
('function', 'exfoliant', 'Exfoliant', 27),
('function', 'skin_conditioning_agent', 'Skin-conditioning agent', 28),
('function', 'hair_conditioning_agent', 'Hair-conditioning agent', 29),
('function', 'tone_support_active', 'Depigmenting or brightening active', 30),
('function', 'soothing_active', 'Soothing active', 31),
('function', 'sebum_control_active', 'Sebum-control active', 32),
('function', 'anti_dandruff_active', 'Anti-dandruff active', 33),
('function', 'nail_conditioning_agent', 'Nail-conditioning agent', 34),
('product_role', 'oil_cleanser', 'Oil cleanser', 1),
('product_role', 'balm_cleanser', 'Balm cleanser', 2),
('product_role', 'water_cleanser', 'Water cleanser', 3),
('product_role', 'exfoliating_cleanser', 'Exfoliating cleanser', 4),
('product_role', 'toner', 'Toner', 5),
('product_role', 'essence', 'Essence', 6),
('product_role', 'hydrating_serum', 'Hydrating serum', 7),
('product_role', 'treatment_serum', 'Treatment serum', 8),
('product_role', 'eye_product', 'Eye product', 9),
('product_role', 'gel_moisturizer', 'Gel moisturizer', 10),
('product_role', 'lotion', 'Lotion', 11),
('product_role', 'cream_moisturizer', 'Cream moisturizer', 12),
('product_role', 'barrier_balm', 'Barrier balm', 13),
('product_role', 'spot_treatment', 'Spot treatment', 14),
('product_role', 'facial_oil', 'Facial oil', 15),
('product_role', 'sunscreen', 'Sunscreen', 16),
('product_role', 'sleeping_mask', 'Sleeping mask', 17),
('product_role', 'wash_off_mask', 'Wash-off mask', 18),
('product_role', 'lip_treatment', 'Lip treatment', 19),
('product_role', 'shampoo', 'Shampoo', 20),
('product_role', 'clarifying_shampoo', 'Clarifying shampoo', 21),
('product_role', 'anti_dandruff_shampoo', 'Anti-dandruff shampoo', 22),
('product_role', 'scalp_treatment', 'Scalp treatment', 23),
('product_role', 'rinse_out_conditioner', 'Rinse-out conditioner', 24),
('product_role', 'hair_mask', 'Hair mask', 25),
('product_role', 'leave_in_conditioner', 'Leave-in conditioner', 26),
('product_role', 'hair_serum', 'Hair serum', 27),
('product_role', 'hair_oil', 'Hair oil', 28),
('product_role', 'heat_protectant', 'Heat protectant', 29),
('product_role', 'styling_cream', 'Styling cream', 30),
('product_role', 'curl_product', 'Curl product', 31),
('product_role', 'hair_spray', 'Hair spray', 32),
('product_role', 'color_protection_treatment', 'Color-protection treatment', 33)
on conflict (taxonomy_key, term_code, version_no)
do update set
  label_en = excluded.label_en,
  sort_order = excluded.sort_order,
  is_active = true,
  updated_at = now();

insert into public.beautydna_rule_versions
  (rule_domain, version_key, version_no, status, configuration, effective_from)
values
  ('ingredient_intelligence', 'beauty-intelligence-ingredient-v1', 1, 'draft',
   '{"customer_data_requires_approved_records":true,"unknown_values_use_null":true,"hard_rules_require_evidence":true}'::jsonb,
   now())
on conflict (rule_domain, version_key, version_no)
do update set configuration = excluded.configuration;

commit;
