begin;

create temporary table tmp_beautydna_core_150 (
  priority_rank integer,
  coverage_tier text,
  canonical_inci_name text,
  normalized_ingredient_name text,
  ingredient_slug text,
  preferred_display_name_en text,
  japanese_labeling_name text,
  ingredient_family text,
  primary_function_summary text,
  common_product_types text[]
) on commit drop;

insert into tmp_beautydna_core_150 values
(1, 'A — foundational / ubiquitous', 'Water', 'water', 'water', 'Water', '水', 'solvent', 'Solvent / vehicle', ARRAY['all product types']::text[]),
(2, 'A — foundational / ubiquitous', 'Glycerin', 'glycerin', 'glycerin', 'Glycerin', 'グリセリン', 'humectant', 'Humectant', ARRAY['lotions','serums','emulsions','masks']::text[]),
(3, 'A — foundational / ubiquitous', 'Butylene Glycol', 'butylene_glycol', 'butylene-glycol', 'Butylene Glycol', 'BG', 'humectant', 'Humectant', ARRAY['lotions','serums','emulsions','masks']::text[]),
(4, 'A — foundational / ubiquitous', 'Dipropylene Glycol', 'dipropylene_glycol', 'dipropylene-glycol', 'Dipropylene Glycol', 'DPG', 'humectant', 'Humectant', ARRAY['lotions','serums','emulsions','masks']::text[]),
(5, 'A — foundational / ubiquitous', 'Ethanol', 'ethanol', 'ethanol', 'Ethanol', 'エタノール', 'solvent', 'Solvent / vehicle', ARRAY['all product types']::text[]),
(6, 'A — foundational / ubiquitous', 'Propanediol', 'propanediol', 'propanediol', 'Propanediol', 'プロパンジオール', 'humectant', 'Humectant', ARRAY['lotions','serums','emulsions','masks']::text[]),
(7, 'A — foundational / ubiquitous', 'Pentylene Glycol', 'pentylene_glycol', 'pentylene-glycol', 'Pentylene Glycol', 'ペンチレングリコール', 'humectant', 'Humectant', ARRAY['lotions','serums','emulsions','masks']::text[]),
(8, 'A — foundational / ubiquitous', '1,2-Hexanediol', '1_2_hexanediol', '1-2-hexanediol', '1,2-Hexanediol', '1,2-ヘキサンジオール', 'humectant_preservative_booster', 'Humectant / preservation support', ARRAY['lotions','serums','gels']::text[]),
(9, 'A — foundational / ubiquitous', 'Diglycerin', 'diglycerin', 'diglycerin', 'Diglycerin', 'ジグリセリン', 'humectant', 'Humectant', ARRAY['lotions','serums','emulsions','masks']::text[]),
(10, 'A — foundational / ubiquitous', 'Sorbitol', 'sorbitol', 'sorbitol', 'Sorbitol', 'ソルビトール', 'humectant', 'Humectant', ARRAY['lotions','serums','emulsions','masks']::text[]),
(11, 'A — foundational / ubiquitous', 'Betaine', 'betaine', 'betaine', 'Betaine', 'ベタイン', 'humectant', 'Humectant', ARRAY['lotions','serums','emulsions','masks']::text[]),
(12, 'A — foundational / ubiquitous', 'Methyl Gluceth-10', 'methyl_gluceth_10', 'methyl-gluceth-10', 'Methyl Gluceth-10', 'メチルグルセス-10', 'humectant', 'Humectant', ARRAY['lotions','serums','emulsions','masks']::text[]),
(13, 'A — foundational / ubiquitous', 'Sodium PCA', 'sodium_pca', 'sodium-pca', 'Sodium PCA', 'PCA-Na', 'humectant', 'Humectant', ARRAY['lotions','serums','emulsions','masks']::text[]),
(14, 'A — foundational / ubiquitous', 'Trehalose', 'trehalose', 'trehalose', 'Trehalose', 'トレハロース', 'humectant', 'Humectant', ARRAY['lotions','serums','emulsions','masks']::text[]),
(15, 'A — foundational / ubiquitous', 'Urea', 'urea', 'urea', 'Urea', '尿素', 'humectant', 'Humectant', ARRAY['lotions','serums','emulsions','masks']::text[]),
(16, 'A — foundational / ubiquitous', 'Sodium Lactate', 'sodium_lactate', 'sodium-lactate', 'Sodium Lactate', '乳酸Na', 'humectant', 'Humectant', ARRAY['lotions','serums','emulsions','masks']::text[]),
(17, 'A — foundational / ubiquitous', 'Arginine', 'arginine', 'arginine', 'Arginine', 'アルギニン', 'amino_acid_ph', 'Amino acid / pH support', ARRAY['cleansers','lotions','creams']::text[]),
(18, 'A — foundational / ubiquitous', 'Citric Acid', 'citric_acid', 'citric-acid', 'Citric Acid', 'クエン酸', 'ph_adjuster', 'pH adjuster', ARRAY['all product types']::text[]),
(19, 'A — foundational / ubiquitous', 'Sodium Citrate', 'sodium_citrate', 'sodium-citrate', 'Sodium Citrate', 'クエン酸Na', 'buffer', 'Buffer', ARRAY['all product types']::text[]),
(20, 'A — foundational / ubiquitous', 'Lactic Acid', 'lactic_acid', 'lactic-acid', 'Lactic Acid', '乳酸', 'ph_adjuster_aha', 'pH adjuster / AHA', ARRAY['lotions','exfoliants','cleansers']::text[]),
(21, 'A — foundational / ubiquitous', 'Potassium Hydroxide', 'potassium_hydroxide', 'potassium-hydroxide', 'Potassium Hydroxide', '水酸化K', 'ph_adjuster', 'pH adjuster', ARRAY['all product types']::text[]),
(22, 'A — foundational / ubiquitous', 'Sodium Hydroxide', 'sodium_hydroxide', 'sodium-hydroxide', 'Sodium Hydroxide', '水酸化Na', 'ph_adjuster', 'pH adjuster', ARRAY['all product types']::text[]),
(23, 'A — foundational / ubiquitous', 'Tromethamine', 'tromethamine', 'tromethamine', 'Tromethamine', 'トロメタミン', 'ph_adjuster', 'pH adjuster', ARRAY['all product types']::text[]),
(24, 'A — foundational / ubiquitous', 'Disodium EDTA', 'disodium_edta', 'disodium-edta', 'Disodium EDTA', 'EDTA-2Na', 'chelating', 'Chelating / stability agent', ARRAY['all product types']::text[]),
(25, 'A — foundational / ubiquitous', 'Phenoxyethanol', 'phenoxyethanol', 'phenoxyethanol', 'Phenoxyethanol', 'フェノキシエタノール', 'preservative', 'Preservative', ARRAY['water-based products']::text[]),
(26, 'A — foundational / ubiquitous', 'Methylparaben', 'methylparaben', 'methylparaben', 'Methylparaben', 'メチルパラベン', 'preservative', 'Preservative', ARRAY['water-based products']::text[]),
(27, 'A — foundational / ubiquitous', 'Propylparaben', 'propylparaben', 'propylparaben', 'Propylparaben', 'プロピルパラベン', 'preservative', 'Preservative', ARRAY['water-based products']::text[]),
(28, 'A — foundational / ubiquitous', 'Sodium Benzoate', 'sodium_benzoate', 'sodium-benzoate', 'Sodium Benzoate', '安息香酸Na', 'preservative', 'Preservative', ARRAY['water-based products']::text[]),
(29, 'A — foundational / ubiquitous', 'Potassium Sorbate', 'potassium_sorbate', 'potassium-sorbate', 'Potassium Sorbate', 'ソルビン酸K', 'preservative', 'Preservative', ARRAY['water-based products']::text[]),
(30, 'A — foundational / ubiquitous', 'Chlorphenesin', 'chlorphenesin', 'chlorphenesin', 'Chlorphenesin', 'クロルフェネシン', 'preservative', 'Preservative', ARRAY['water-based products']::text[]),
(31, 'A — foundational / ubiquitous', 'Benzyl Alcohol', 'benzyl_alcohol', 'benzyl-alcohol', 'Benzyl Alcohol', 'ベンジルアルコール', 'preservative_solvent', 'Preservative / solvent', ARRAY['water-based products']::text[]),
(32, 'A — foundational / ubiquitous', 'Ethylhexylglycerin', 'ethylhexylglycerin', 'ethylhexylglycerin', 'Ethylhexylglycerin', 'エチルヘキシルグリセリン', 'preservative_booster', 'Preservation support / humectant', ARRAY['water-based products']::text[]),
(33, 'A — foundational / ubiquitous', 'Caprylyl Glycol', 'caprylyl_glycol', 'caprylyl-glycol', 'Caprylyl Glycol', 'カプリリルグリコール', 'preservative_booster', 'Preservation support / humectant', ARRAY['water-based products']::text[]),
(34, 'A — foundational / ubiquitous', 'Fragrance', 'fragrance', 'fragrance', 'Fragrance', '香料', 'fragrance', 'Fragrance', ARRAY['fragranced products']::text[]),
(35, 'A — foundational / ubiquitous', 'Tocopherol', 'tocopherol', 'tocopherol', 'Tocopherol', 'トコフェロール', 'antioxidant', 'Formula antioxidant', ARRAY['oils','emulsions','sunscreens']::text[]),
(36, 'A — foundational / ubiquitous', 'BHT', 'bht', 'bht', 'BHT', 'BHT', 'antioxidant', 'Formula antioxidant', ARRAY['oils','emulsions','sunscreens']::text[]),
(37, 'A — foundational / ubiquitous', 'Sodium Metabisulfite', 'sodium_metabisulfite', 'sodium-metabisulfite', 'Sodium Metabisulfite', 'ピロ亜硫酸Na', 'antioxidant', 'Formula antioxidant', ARRAY['oils','emulsions','sunscreens']::text[]),
(38, 'A — foundational / ubiquitous', 'Dehydroacetic Acid', 'dehydroacetic_acid', 'dehydroacetic-acid', 'Dehydroacetic Acid', 'デヒドロ酢酸', 'preservative', 'Preservative', ARRAY['water-based products']::text[]),
(39, 'A — foundational / ubiquitous', 'Sodium Phytate', 'sodium_phytate', 'sodium-phytate', 'Sodium Phytate', 'フィチン酸Na', 'chelating', 'Chelating / stability agent', ARRAY['all product types']::text[]),
(40, 'A — foundational / ubiquitous', 'Phytic Acid', 'phytic_acid', 'phytic-acid', 'Phytic Acid', 'フィチン酸', 'chelating', 'Chelating / stability agent', ARRAY['all product types']::text[]),
(41, 'B — very common formulation support', 'Carbomer', 'carbomer', 'carbomer', 'Carbomer', 'カルボマー', 'thickener', 'Viscosity control / gel former', ARRAY['gels','lotions','serums','emulsions']::text[]),
(42, 'B — very common formulation support', 'Xanthan Gum', 'xanthan_gum', 'xanthan-gum', 'Xanthan Gum', 'キサンタンガム', 'thickener', 'Viscosity control / gel former', ARRAY['gels','lotions','serums','emulsions']::text[]),
(43, 'B — very common formulation support', 'Hydroxyethylcellulose', 'hydroxyethylcellulose', 'hydroxyethylcellulose', 'Hydroxyethylcellulose', 'ヒドロキシエチルセルロース', 'thickener', 'Viscosity control / gel former', ARRAY['gels','lotions','serums','emulsions']::text[]),
(44, 'B — very common formulation support', 'Cellulose Gum', 'cellulose_gum', 'cellulose-gum', 'Cellulose Gum', 'セルロースガム', 'thickener', 'Viscosity control / gel former', ARRAY['gels','lotions','serums','emulsions']::text[]),
(45, 'B — very common formulation support', 'Sodium Polyacrylate', 'sodium_polyacrylate', 'sodium-polyacrylate', 'Sodium Polyacrylate', 'ポリアクリル酸Na', 'thickener_film', 'Thickener / film former', ARRAY['gels','lotions','masks']::text[]),
(46, 'B — very common formulation support', 'Acrylates/C10-30 Alkyl Acrylate Crosspolymer', 'acrylates_c10_30_alkyl_acrylate_crosspolymer', 'acrylates-c10-30-alkyl-acrylate-crosspolymer', 'Acrylates/C10-30 Alkyl Acrylate Crosspolymer', '（アクリレーツ／アクリル酸アルキル（C10-30））クロスポリマー', 'thickener', 'Viscosity control / gel former', ARRAY['gels','lotions','serums','emulsions']::text[]),
(47, 'B — very common formulation support', 'Ammonium Acryloyldimethyltaurate/VP Copolymer', 'ammonium_acryloyldimethyltaurate_vp_copolymer', 'ammonium-acryloyldimethyltaurate-vp-copolymer', 'Ammonium Acryloyldimethyltaurate/VP Copolymer', '（アクリロイルジメチルタウリンアンモニウム／VP）コポリマー', 'thickener', 'Viscosity control / gel former', ARRAY['gels','lotions','serums','emulsions']::text[]),
(48, 'B — very common formulation support', 'Polyacrylate Crosspolymer-6', 'polyacrylate_crosspolymer_6', 'polyacrylate-crosspolymer-6', 'Polyacrylate Crosspolymer-6', 'ポリアクリレートクロスポリマー-6', 'thickener', 'Viscosity control / gel former', ARRAY['gels','lotions','serums','emulsions']::text[]),
(49, 'B — very common formulation support', 'Polyacrylamide', 'polyacrylamide', 'polyacrylamide', 'Polyacrylamide', 'ポリアクリルアミド', 'thickener', 'Viscosity control / gel former', ARRAY['gels','lotions','serums','emulsions']::text[]),
(50, 'B — very common formulation support', 'C13-14 Isoparaffin', 'c13_14_isoparaffin', 'c13-14-isoparaffin', 'C13-14 Isoparaffin', 'C13-14イソパラフィン', 'emollient', 'Emollient', ARRAY['cleansers','creams','sunscreens','makeup']::text[]),
(51, 'B — very common formulation support', 'Laureth-7', 'laureth_7', 'laureth-7', 'Laureth-7', 'ラウレス-7', 'surfactant', 'Surfactant / emulsifier', ARRAY['cleansers','emulsions']::text[]),
(52, 'B — very common formulation support', 'Silica', 'silica', 'silica', 'Silica', 'シリカ', 'absorbent_texture', 'Absorbent / texture modifier', ARRAY['sunscreens','primers','powders']::text[]),
(53, 'B — very common formulation support', 'Dimethicone', 'dimethicone', 'dimethicone', 'Dimethicone', 'ジメチコン', 'silicone_emollient', 'Silicone emollient', ARRAY['serums','creams','sunscreens','makeup']::text[]),
(54, 'B — very common formulation support', 'Cyclopentasiloxane', 'cyclopentasiloxane', 'cyclopentasiloxane', 'Cyclopentasiloxane', 'シクロペンタシロキサン', 'volatile_silicone', 'Volatile silicone', ARRAY['sunscreens','serums','makeup']::text[]),
(55, 'B — very common formulation support', 'Phenyl Trimethicone', 'phenyl_trimethicone', 'phenyl-trimethicone', 'Phenyl Trimethicone', 'フェニルトリメチコン', 'silicone_emollient', 'Silicone emollient', ARRAY['serums','creams','sunscreens','makeup']::text[]),
(56, 'B — very common formulation support', 'Dimethicone/Vinyl Dimethicone Crosspolymer', 'dimethicone_vinyl_dimethicone_crosspolymer', 'dimethicone-vinyl-dimethicone-crosspolymer', 'Dimethicone/Vinyl Dimethicone Crosspolymer', '（ジメチコン／ビニルジメチコン）クロスポリマー', 'silicone_texture', 'Silicone elastomer / texture modifier', ARRAY['sunscreens','primers','creams']::text[]),
(57, 'B — very common formulation support', 'Trimethylsiloxysilicate', 'trimethylsiloxysilicate', 'trimethylsiloxysilicate', 'Trimethylsiloxysilicate', 'トリメチルシロキシケイ酸', 'film_former', 'Film former', ARRAY['sunscreens','makeup','masks']::text[]),
(58, 'B — very common formulation support', 'PEG-10 Dimethicone', 'peg_10_dimethicone', 'peg-10-dimethicone', 'PEG-10 Dimethicone', 'PEG-10ジメチコン', 'silicone_emulsifier', 'Silicone emulsifier', ARRAY['sunscreens','makeup','emulsions']::text[]),
(59, 'B — very common formulation support', 'Hydrogen Dimethicone', 'hydrogen_dimethicone', 'hydrogen-dimethicone', 'Hydrogen Dimethicone', 'ハイドロゲンジメチコン', 'silicone_surface_treatment', 'Surface treatment / water resistance aid', ARRAY['sunscreens','makeup']::text[]),
(60, 'B — very common formulation support', 'Squalane', 'squalane', 'squalane', 'Squalane', 'スクワラン', 'emollient', 'Emollient', ARRAY['cleansers','creams','sunscreens','makeup']::text[]),
(61, 'B — very common formulation support', 'Mineral Oil', 'mineral_oil', 'mineral-oil', 'Mineral Oil', 'ミネラルオイル', 'occlusive_emollient', 'Occlusive emollient', ARRAY['creams','balms','cleansing oils']::text[]),
(62, 'B — very common formulation support', 'Petrolatum', 'petrolatum', 'petrolatum', 'Petrolatum', 'ワセリン', 'occlusive', 'Occlusive', ARRAY['balms','creams','lip care']::text[]),
(63, 'B — very common formulation support', 'Caprylic/Capric Triglyceride', 'caprylic_capric_triglyceride', 'caprylic-capric-triglyceride', 'Caprylic/Capric Triglyceride', 'トリ（カプリル酸／カプリン酸）グリセリル', 'emollient', 'Emollient', ARRAY['cleansers','creams','sunscreens','makeup']::text[]),
(64, 'B — very common formulation support', 'Triethylhexanoin', 'triethylhexanoin', 'triethylhexanoin', 'Triethylhexanoin', 'トリエチルヘキサノイン', 'emollient', 'Emollient', ARRAY['cleansers','creams','sunscreens','makeup']::text[]),
(65, 'B — very common formulation support', 'Cetyl Ethylhexanoate', 'cetyl_ethylhexanoate', 'cetyl-ethylhexanoate', 'Cetyl Ethylhexanoate', 'エチルヘキサン酸セチル', 'emollient', 'Emollient', ARRAY['cleansers','creams','sunscreens','makeup']::text[]),
(66, 'B — very common formulation support', 'Ethylhexyl Palmitate', 'ethylhexyl_palmitate', 'ethylhexyl-palmitate', 'Ethylhexyl Palmitate', 'パルミチン酸エチルヘキシル', 'emollient', 'Emollient', ARRAY['cleansers','creams','sunscreens','makeup']::text[]),
(67, 'B — very common formulation support', 'Isononyl Isononanoate', 'isononyl_isononanoate', 'isononyl-isononanoate', 'Isononyl Isononanoate', 'イソノナン酸イソノニル', 'emollient', 'Emollient', ARRAY['cleansers','creams','sunscreens','makeup']::text[]),
(68, 'B — very common formulation support', 'Dicaprylyl Carbonate', 'dicaprylyl_carbonate', 'dicaprylyl-carbonate', 'Dicaprylyl Carbonate', '炭酸ジカプリリル', 'emollient', 'Emollient', ARRAY['cleansers','creams','sunscreens','makeup']::text[]),
(69, 'B — very common formulation support', 'C12-15 Alkyl Benzoate', 'c12_15_alkyl_benzoate', 'c12-15-alkyl-benzoate', 'C12-15 Alkyl Benzoate', '安息香酸アルキル（C12-15）', 'emollient', 'Emollient', ARRAY['cleansers','creams','sunscreens','makeup']::text[]),
(70, 'B — very common formulation support', 'Isododecane', 'isododecane', 'isododecane', 'Isododecane', 'イソドデカン', 'volatile_emollient', 'Volatile emollient / solvent', ARRAY['sunscreens','makeup']::text[]),
(71, 'B — very common formulation support', 'Hydrogenated Polyisobutene', 'hydrogenated_polyisobutene', 'hydrogenated-polyisobutene', 'Hydrogenated Polyisobutene', '水添ポリイソブテン', 'emollient', 'Emollient', ARRAY['cleansers','creams','sunscreens','makeup']::text[]),
(72, 'B — very common formulation support', 'Simmondsia Chinensis (Jojoba) Seed Oil', 'simmondsia_chinensis_jojoba_seed_oil', 'simmondsia-chinensis-jojoba-seed-oil', 'Simmondsia Chinensis (Jojoba) Seed Oil', 'ホホバ種子油', 'plant_oil', 'Plant oil / emollient', ARRAY['cleansing oils','creams','hair care']::text[]),
(73, 'B — very common formulation support', 'Camellia Japonica Seed Oil', 'camellia_japonica_seed_oil', 'camellia-japonica-seed-oil', 'Camellia Japonica Seed Oil', 'ツバキ種子油', 'plant_oil', 'Plant oil / emollient', ARRAY['cleansing oils','creams','hair care']::text[]),
(74, 'B — very common formulation support', 'Oryza Sativa (Rice) Bran Oil', 'oryza_sativa_rice_bran_oil', 'oryza-sativa-rice-bran-oil', 'Oryza Sativa (Rice) Bran Oil', 'コメヌカ油', 'plant_oil', 'Plant oil / emollient', ARRAY['cleansing oils','creams','hair care']::text[]),
(75, 'B — very common formulation support', 'Olea Europaea (Olive) Fruit Oil', 'olea_europaea_olive_fruit_oil', 'olea-europaea-olive-fruit-oil', 'Olea Europaea (Olive) Fruit Oil', 'オリーブ果実油', 'plant_oil', 'Plant oil / emollient', ARRAY['cleansing oils','creams','hair care']::text[]),
(76, 'B — very common formulation support', 'Butyrospermum Parkii (Shea) Butter', 'butyrospermum_parkii_shea_butter', 'butyrospermum-parkii-shea-butter', 'Butyrospermum Parkii (Shea) Butter', 'シア脂', 'plant_butter', 'Plant butter / occlusive emollient', ARRAY['creams','balms']::text[]),
(77, 'B — very common formulation support', 'Cetyl Alcohol', 'cetyl_alcohol', 'cetyl-alcohol', 'Cetyl Alcohol', 'セタノール', 'fatty_alcohol', 'Fatty alcohol / consistency agent', ARRAY['creams','emulsions','conditioners']::text[]),
(78, 'B — very common formulation support', 'Stearyl Alcohol', 'stearyl_alcohol', 'stearyl-alcohol', 'Stearyl Alcohol', 'ステアリルアルコール', 'fatty_alcohol', 'Fatty alcohol / consistency agent', ARRAY['creams','emulsions','conditioners']::text[]),
(79, 'B — very common formulation support', 'Behenyl Alcohol', 'behenyl_alcohol', 'behenyl-alcohol', 'Behenyl Alcohol', 'ベヘニルアルコール', 'fatty_alcohol', 'Fatty alcohol / consistency agent', ARRAY['creams','emulsions','conditioners']::text[]),
(80, 'B — very common formulation support', 'Cetearyl Alcohol', 'cetearyl_alcohol', 'cetearyl-alcohol', 'Cetearyl Alcohol', 'セテアリルアルコール', 'fatty_alcohol', 'Fatty alcohol / consistency agent', ARRAY['creams','emulsions','conditioners']::text[]),
(81, 'B — very common formulation support', 'Stearic Acid', 'stearic_acid', 'stearic-acid', 'Stearic Acid', 'ステアリン酸', 'fatty_acid', 'Fatty acid / cleanser or emulsion component', ARRAY['foam cleansers','soaps','creams']::text[]),
(82, 'B — very common formulation support', 'Palmitic Acid', 'palmitic_acid', 'palmitic-acid', 'Palmitic Acid', 'パルミチン酸', 'fatty_acid', 'Fatty acid / cleanser or emulsion component', ARRAY['foam cleansers','soaps','creams']::text[]),
(83, 'B — very common formulation support', 'Myristic Acid', 'myristic_acid', 'myristic-acid', 'Myristic Acid', 'ミリスチン酸', 'fatty_acid', 'Fatty acid / cleanser or emulsion component', ARRAY['foam cleansers','soaps','creams']::text[]),
(84, 'B — very common formulation support', 'Lauric Acid', 'lauric_acid', 'lauric-acid', 'Lauric Acid', 'ラウリン酸', 'fatty_acid', 'Fatty acid / cleanser or emulsion component', ARRAY['foam cleansers','soaps','creams']::text[]),
(85, 'B — very common formulation support', 'Oleic Acid', 'oleic_acid', 'oleic-acid', 'Oleic Acid', 'オレイン酸', 'fatty_acid', 'Fatty acid / cleanser or emulsion component', ARRAY['foam cleansers','soaps','creams']::text[]),
(86, 'B — very common formulation support', 'Glyceryl Stearate', 'glyceryl_stearate', 'glyceryl-stearate', 'Glyceryl Stearate', 'ステアリン酸グリセリル', 'emulsifier', 'Emulsifier', ARRAY['creams','milks','cleansing oils']::text[]),
(87, 'B — very common formulation support', 'PEG-100 Stearate', 'peg_100_stearate', 'peg-100-stearate', 'PEG-100 Stearate', 'ステアリン酸PEG-100', 'emulsifier', 'Emulsifier', ARRAY['creams','milks','cleansing oils']::text[]),
(88, 'B — very common formulation support', 'Sorbitan Stearate', 'sorbitan_stearate', 'sorbitan-stearate', 'Sorbitan Stearate', 'ステアリン酸ソルビタン', 'emulsifier', 'Emulsifier', ARRAY['creams','milks','cleansing oils']::text[]),
(89, 'B — very common formulation support', 'Sucrose Stearate', 'sucrose_stearate', 'sucrose-stearate', 'Sucrose Stearate', 'ステアリン酸スクロース', 'emulsifier', 'Emulsifier', ARRAY['creams','milks','cleansing oils']::text[]),
(90, 'B — very common formulation support', 'Hydrogenated Lecithin', 'hydrogenated_lecithin', 'hydrogenated-lecithin', 'Hydrogenated Lecithin', '水添レシチン', 'emulsifier_barrier', 'Emulsifier / phospholipid', ARRAY['serums','creams','liposomes']::text[]),
(91, 'B — very common formulation support', 'Lecithin', 'lecithin', 'lecithin', 'Lecithin', 'レシチン', 'emulsifier', 'Emulsifier', ARRAY['creams','milks','cleansing oils']::text[]),
(92, 'B — very common formulation support', 'PEG-60 Hydrogenated Castor Oil', 'peg_60_hydrogenated_castor_oil', 'peg-60-hydrogenated-castor-oil', 'PEG-60 Hydrogenated Castor Oil', 'PEG-60水添ヒマシ油', 'solubilizer', 'Solubilizer', ARRAY['lotions','mists','cleansers']::text[]),
(93, 'B — very common formulation support', 'PEG-40 Hydrogenated Castor Oil', 'peg_40_hydrogenated_castor_oil', 'peg-40-hydrogenated-castor-oil', 'PEG-40 Hydrogenated Castor Oil', 'PEG-40水添ヒマシ油', 'solubilizer', 'Solubilizer', ARRAY['lotions','mists','cleansers']::text[]),
(94, 'B — very common formulation support', 'Polysorbate 20', 'polysorbate_20', 'polysorbate-20', 'Polysorbate 20', 'ポリソルベート20', 'solubilizer', 'Solubilizer', ARRAY['lotions','mists','cleansers']::text[]),
(95, 'B — very common formulation support', 'Polysorbate 60', 'polysorbate_60', 'polysorbate-60', 'Polysorbate 60', 'ポリソルベート60', 'emulsifier', 'Emulsifier', ARRAY['creams','milks','cleansing oils']::text[]),
(96, 'B — very common formulation support', 'Polysorbate 80', 'polysorbate_80', 'polysorbate-80', 'Polysorbate 80', 'ポリソルベート80', 'emulsifier', 'Emulsifier', ARRAY['creams','milks','cleansing oils']::text[]),
(97, 'B — very common formulation support', 'Polyglyceryl-10 Laurate', 'polyglyceryl_10_laurate', 'polyglyceryl-10-laurate', 'Polyglyceryl-10 Laurate', 'ラウリン酸ポリグリセリル-10', 'emulsifier_surfactant', 'Emulsifier / mild surfactant', ARRAY['cleansers','lotions','emulsions']::text[]),
(98, 'B — very common formulation support', 'Polyglyceryl-10 Myristate', 'polyglyceryl_10_myristate', 'polyglyceryl-10-myristate', 'Polyglyceryl-10 Myristate', 'ミリスチン酸ポリグリセリル-10', 'emulsifier_surfactant', 'Emulsifier / mild surfactant', ARRAY['cleansers','lotions','emulsions']::text[]),
(99, 'B — very common formulation support', 'Polyglyceryl-2 Diisostearate', 'polyglyceryl_2_diisostearate', 'polyglyceryl-2-diisostearate', 'Polyglyceryl-2 Diisostearate', 'ジイソステアリン酸ポリグリセリル-2', 'emulsifier', 'Emulsifier', ARRAY['creams','milks','cleansing oils']::text[]),
(100, 'B — very common formulation support', 'Glyceryl Caprylate', 'glyceryl_caprylate', 'glyceryl-caprylate', 'Glyceryl Caprylate', 'カプリル酸グリセリル', 'emollient_preservative_booster', 'Emollient / preservation support', ARRAY['emulsions','cleansers']::text[]),
(101, 'C — category-common cleansing', 'Sorbitan Oleate', 'sorbitan_oleate', 'sorbitan-oleate', 'Sorbitan Oleate', 'オレイン酸ソルビタン', 'emulsifier', 'Emulsifier', ARRAY['creams','milks','cleansing oils']::text[]),
(102, 'C — category-common cleansing', 'Aluminum Hydroxide', 'aluminum_hydroxide', 'aluminum-hydroxide', 'Aluminum Hydroxide', '水酸化Al', 'uv_pigment_coating', 'Mineral coating / dispersion aid', ARRAY['sunscreens','makeup']::text[]),
(103, 'C — category-common cleansing', 'Sodium Cocoyl Glycinate', 'sodium_cocoyl_glycinate', 'sodium-cocoyl-glycinate', 'Sodium Cocoyl Glycinate', 'ココイルグリシンNa', 'amino_acid_surfactant', 'Amino-acid surfactant', ARRAY['facial cleansers','body wash']::text[]),
(104, 'C — category-common cleansing', 'Potassium Cocoyl Glycinate', 'potassium_cocoyl_glycinate', 'potassium-cocoyl-glycinate', 'Potassium Cocoyl Glycinate', 'ココイルグリシンK', 'amino_acid_surfactant', 'Amino-acid surfactant', ARRAY['facial cleansers','body wash']::text[]),
(105, 'C — category-common cleansing', 'Sodium Cocoyl Glutamate', 'sodium_cocoyl_glutamate', 'sodium-cocoyl-glutamate', 'Sodium Cocoyl Glutamate', 'ココイルグルタミン酸Na', 'amino_acid_surfactant', 'Amino-acid surfactant', ARRAY['facial cleansers','body wash']::text[]),
(106, 'C — category-common cleansing', 'Disodium Cocoyl Glutamate', 'disodium_cocoyl_glutamate', 'disodium-cocoyl-glutamate', 'Disodium Cocoyl Glutamate', 'ココイルグルタミン酸2Na', 'amino_acid_surfactant', 'Amino-acid surfactant', ARRAY['facial cleansers','body wash']::text[]),
(107, 'C — category-common cleansing', 'Sodium Lauroyl Glutamate', 'sodium_lauroyl_glutamate', 'sodium-lauroyl-glutamate', 'Sodium Lauroyl Glutamate', 'ラウロイルグルタミン酸Na', 'amino_acid_surfactant', 'Amino-acid surfactant', ARRAY['facial cleansers','body wash']::text[]),
(108, 'C — category-common cleansing', 'Sodium Methyl Cocoyl Taurate', 'sodium_methyl_cocoyl_taurate', 'sodium-methyl-cocoyl-taurate', 'Sodium Methyl Cocoyl Taurate', 'ココイルメチルタウリンNa', 'taurate_surfactant', 'Taurate surfactant', ARRAY['facial cleansers','shampoos']::text[]),
(109, 'C — category-common cleansing', 'Sodium Lauroyl Methyl Taurate', 'sodium_lauroyl_methyl_taurate', 'sodium-lauroyl-methyl-taurate', 'Sodium Lauroyl Methyl Taurate', 'ラウロイルメチルタウリンNa', 'taurate_surfactant', 'Taurate surfactant', ARRAY['facial cleansers','shampoos']::text[]),
(110, 'C — category-common cleansing', 'Sodium Lauroyl Methylaminopropionate', 'sodium_lauroyl_methylaminopropionate', 'sodium-lauroyl-methylaminopropionate', 'Sodium Lauroyl Methylaminopropionate', 'ラウロイルメチルアラニンNa', 'amino_acid_surfactant', 'Amino-acid surfactant', ARRAY['facial cleansers','body wash']::text[]),
(111, 'C — category-common cleansing', 'Cocamidopropyl Betaine', 'cocamidopropyl_betaine', 'cocamidopropyl-betaine', 'Cocamidopropyl Betaine', 'コカミドプロピルベタイン', 'amphoteric_surfactant', 'Amphoteric surfactant', ARRAY['cleansers','shampoos']::text[]),
(112, 'C — category-common cleansing', 'Lauryl Betaine', 'lauryl_betaine', 'lauryl-betaine', 'Lauryl Betaine', 'ラウリルベタイン', 'amphoteric_surfactant', 'Amphoteric surfactant', ARRAY['cleansers','shampoos']::text[]),
(113, 'C — category-common cleansing', 'Sodium Cocoyl Isethionate', 'sodium_cocoyl_isethionate', 'sodium-cocoyl-isethionate', 'Sodium Cocoyl Isethionate', 'ココイルイセチオン酸Na', 'anionic_surfactant', 'Anionic surfactant', ARRAY['cleansers','shampoos']::text[]),
(114, 'C — category-common cleansing', 'Sodium Laureth Sulfate', 'sodium_laureth_sulfate', 'sodium-laureth-sulfate', 'Sodium Laureth Sulfate', 'ラウレス硫酸Na', 'anionic_surfactant', 'Anionic surfactant', ARRAY['cleansers','shampoos']::text[]),
(115, 'C — category-common cleansing', 'Decyl Glucoside', 'decyl_glucoside', 'decyl-glucoside', 'Decyl Glucoside', 'デシルグルコシド', 'nonionic_surfactant', 'Nonionic sugar surfactant', ARRAY['gentle cleansers']::text[]),
(116, 'C — category-common cleansing', 'Coco-Glucoside', 'coco_glucoside', 'coco-glucoside', 'Coco-Glucoside', 'ココイルグルコシド', 'nonionic_surfactant', 'Nonionic sugar surfactant', ARRAY['gentle cleansers']::text[]),
(117, 'C — category-common cleansing', 'Potassium Myristate', 'potassium_myristate', 'potassium-myristate', 'Potassium Myristate', 'ミリスチン酸K', 'soap_surfactant', 'Soap surfactant', ARRAY['Japanese foaming facial cleansers']::text[]),
(118, 'C — category-common cleansing', 'Potassium Stearate', 'potassium_stearate', 'potassium-stearate', 'Potassium Stearate', 'ステアリン酸K', 'soap_surfactant', 'Soap surfactant', ARRAY['Japanese foaming facial cleansers']::text[]),
(119, 'C — category-common cleansing', 'Potassium Palmitate', 'potassium_palmitate', 'potassium-palmitate', 'Potassium Palmitate', 'パルミチン酸K', 'soap_surfactant', 'Soap surfactant', ARRAY['Japanese foaming facial cleansers']::text[]),
(120, 'C — category-common cleansing', 'Potassium Laurate', 'potassium_laurate', 'potassium-laurate', 'Potassium Laurate', 'ラウリン酸K', 'soap_surfactant', 'Soap surfactant', ARRAY['Japanese foaming facial cleansers']::text[]),
(121, 'C — category-common cleansing', 'PEG-7 Glyceryl Cocoate', 'peg_7_glyceryl_cocoate', 'peg-7-glyceryl-cocoate', 'PEG-7 Glyceryl Cocoate', 'ヤシ油脂肪酸PEG-7グリセリル', 'refatting_surfactant', 'Refatting surfactant / emollient cleanser aid', ARRAY['cleansers','cleansing oils']::text[]),
(122, 'D — high-value skin intelligence', 'Sodium Hyaluronate', 'sodium_hyaluronate', 'sodium-hyaluronate', 'Sodium Hyaluronate', 'ヒアルロン酸Na', 'humectant_active', 'Hydrating active / humectant', ARRAY['lotions','serums','masks']::text[]),
(123, 'D — high-value skin intelligence', 'Hydrolyzed Hyaluronic Acid', 'hydrolyzed_hyaluronic_acid', 'hydrolyzed-hyaluronic-acid', 'Hydrolyzed Hyaluronic Acid', '加水分解ヒアルロン酸', 'humectant_active', 'Hydrating active / humectant', ARRAY['lotions','serums','masks']::text[]),
(124, 'D — high-value skin intelligence', 'Sodium Acetylated Hyaluronate', 'sodium_acetylated_hyaluronate', 'sodium-acetylated-hyaluronate', 'Sodium Acetylated Hyaluronate', 'アセチルヒアルロン酸Na', 'humectant_active', 'Hydrating active / humectant', ARRAY['lotions','serums','masks']::text[]),
(125, 'D — high-value skin intelligence', 'Niacinamide', 'niacinamide', 'niacinamide', 'Niacinamide', 'ナイアシンアミド', 'multifunctional_active', 'Multifunctional skin-conditioning active', ARRAY['lotions','serums','creams']::text[]),
(126, 'D — high-value skin intelligence', 'Ascorbic Acid', 'ascorbic_acid', 'ascorbic-acid', 'Ascorbic Acid', 'アスコルビン酸', 'antioxidant_active', 'Antioxidant active', ARRAY['serums','lotions','creams']::text[]),
(127, 'D — high-value skin intelligence', 'Ascorbyl Glucoside', 'ascorbyl_glucoside', 'ascorbyl-glucoside', 'Ascorbyl Glucoside', 'アスコルビルグルコシド', 'vitamin_c_derivative', 'Vitamin C derivative', ARRAY['serums','lotions','creams']::text[]),
(128, 'D — high-value skin intelligence', '3-O-Ethyl Ascorbic Acid', '3_o_ethyl_ascorbic_acid', '3-o-ethyl-ascorbic-acid', '3-O-Ethyl Ascorbic Acid', '3-O-エチルアスコルビン酸', 'vitamin_c_derivative', 'Vitamin C derivative', ARRAY['serums','lotions','creams']::text[]),
(129, 'D — high-value skin intelligence', 'Tocopheryl Acetate', 'tocopheryl_acetate', 'tocopheryl-acetate', 'Tocopheryl Acetate', '酢酸トコフェロール', 'antioxidant_active', 'Antioxidant active', ARRAY['serums','lotions','creams']::text[]),
(130, 'D — high-value skin intelligence', 'Tranexamic Acid', 'tranexamic_acid', 'tranexamic-acid', 'Tranexamic Acid', 'トラネキサム酸', 'quasi_drug_active', 'Japanese quasi-drug active / skin conditioning', ARRAY['medicated lotions','serums','emulsions']::text[]),
(131, 'D — high-value skin intelligence', 'Dipotassium Glycyrrhizate', 'dipotassium_glycyrrhizate', 'dipotassium-glycyrrhizate', 'Dipotassium Glycyrrhizate', 'グリチルリチン酸2K', 'soothing_active', 'Soothing / skin-conditioning active', ARRAY['lotions','creams','medicated products']::text[]),
(132, 'D — high-value skin intelligence', 'Stearyl Glycyrrhetinate', 'stearyl_glycyrrhetinate', 'stearyl-glycyrrhetinate', 'Stearyl Glycyrrhetinate', 'グリチルレチン酸ステアリル', 'soothing_active', 'Soothing / skin-conditioning active', ARRAY['lotions','creams','medicated products']::text[]),
(133, 'D — high-value skin intelligence', 'Allantoin', 'allantoin', 'allantoin', 'Allantoin', 'アラントイン', 'soothing_active', 'Soothing / skin-conditioning active', ARRAY['lotions','creams','medicated products']::text[]),
(134, 'D — high-value skin intelligence', 'Panthenol', 'panthenol', 'panthenol', 'Panthenol', 'パンテノール', 'soothing_humectant', 'Soothing humectant', ARRAY['serums','creams','masks']::text[]),
(135, 'D — high-value skin intelligence', 'Arbutin', 'arbutin', 'arbutin', 'Arbutin', 'アルブチン', 'brightening_active', 'Tone-support active', ARRAY['lotions','serums','medicated products']::text[]),
(136, 'D — high-value skin intelligence', 'Salicylic Acid', 'salicylic_acid', 'salicylic-acid', 'Salicylic Acid', 'サリチル酸', 'exfoliant_active', 'Exfoliant / keratolytic active', ARRAY['acne care','cleansers','toners']::text[]),
(137, 'D — high-value skin intelligence', 'Ceramide NP', 'ceramide_np', 'ceramide-np', 'Ceramide NP', 'セラミドNP', 'barrier_lipid', 'Barrier lipid', ARRAY['creams','emulsions','serums']::text[]),
(138, 'D — high-value skin intelligence', 'Hydrolyzed Collagen', 'hydrolyzed_collagen', 'hydrolyzed-collagen', 'Hydrolyzed Collagen', '加水分解コラーゲン', 'film_humectant', 'Film-forming humectant', ARRAY['lotions','masks','creams']::text[]),
(139, 'D — high-value skin intelligence', 'Camellia Sinensis Leaf Extract', 'camellia_sinensis_leaf_extract', 'camellia-sinensis-leaf-extract', 'Camellia Sinensis Leaf Extract', 'チャ葉エキス', 'botanical_antioxidant', 'Botanical antioxidant / skin conditioner', ARRAY['lotions','serums','creams']::text[]),
(140, 'D — high-value skin intelligence', 'Coix Lacryma-Jobi Ma-yuen Seed Extract', 'coix_lacryma_jobi_ma_yuen_seed_extract', 'coix-lacryma-jobi-ma-yuen-seed-extract', 'Coix Lacryma-Jobi Ma-yuen Seed Extract', 'ハトムギ種子エキス', 'jbeauty_botanical', 'J-beauty botanical / skin conditioner', ARRAY['Japanese lotions','gels','masks']::text[]),
(141, 'E — Japanese sunscreen launch coverage', 'Zinc Oxide', 'zinc_oxide', 'zinc-oxide', 'Zinc Oxide', '酸化亜鉛', 'uv_filter_mineral', 'Mineral UV filter / pigment', ARRAY['sunscreens','makeup']::text[]),
(142, 'E — Japanese sunscreen launch coverage', 'Titanium Dioxide', 'titanium_dioxide', 'titanium-dioxide', 'Titanium Dioxide', '酸化チタン', 'uv_filter_mineral', 'Mineral UV filter / pigment', ARRAY['sunscreens','makeup']::text[]),
(143, 'E — Japanese sunscreen launch coverage', 'Ethylhexyl Methoxycinnamate', 'ethylhexyl_methoxycinnamate', 'ethylhexyl-methoxycinnamate', 'Ethylhexyl Methoxycinnamate', 'メトキシケイヒ酸エチルヘキシル', 'uv_filter_organic', 'Organic UV filter', ARRAY['sunscreens','makeup']::text[]),
(144, 'E — Japanese sunscreen launch coverage', 'Ethylhexyl Triazone', 'ethylhexyl_triazone', 'ethylhexyl-triazone', 'Ethylhexyl Triazone', 'エチルヘキシルトリアゾン', 'uv_filter_organic', 'Organic UV filter', ARRAY['sunscreens','makeup']::text[]),
(145, 'E — Japanese sunscreen launch coverage', 'Diethylamino Hydroxybenzoyl Hexyl Benzoate', 'diethylamino_hydroxybenzoyl_hexyl_benzoate', 'diethylamino-hydroxybenzoyl-hexyl-benzoate', 'Diethylamino Hydroxybenzoyl Hexyl Benzoate', 'ジエチルアミノヒドロキシベンゾイル安息香酸ヘキシル', 'uv_filter_organic', 'Organic UV filter', ARRAY['sunscreens','makeup']::text[]),
(146, 'E — Japanese sunscreen launch coverage', 'Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine', 'bis_ethylhexyloxyphenol_methoxyphenyl_triazine', 'bis-ethylhexyloxyphenol-methoxyphenyl-triazine', 'Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine', 'ビスエチルヘキシルオキシフェノールメトキシフェニルトリアジン', 'uv_filter_organic', 'Organic UV filter', ARRAY['sunscreens','makeup']::text[]),
(147, 'E — Japanese sunscreen launch coverage', 'Octocrylene', 'octocrylene', 'octocrylene', 'Octocrylene', 'オクトクリレン', 'uv_filter_organic', 'Organic UV filter', ARRAY['sunscreens','makeup']::text[]),
(148, 'E — Japanese sunscreen launch coverage', 'Polysilicone-15', 'polysilicone_15', 'polysilicone-15', 'Polysilicone-15', 'ポリシリコーン-15', 'uv_filter_organic', 'Organic UV filter', ARRAY['sunscreens','makeup']::text[]),
(149, 'E — Japanese sunscreen launch coverage', 'Butyl Methoxydibenzoylmethane', 'butyl_methoxydibenzoylmethane', 'butyl-methoxydibenzoylmethane', 'Butyl Methoxydibenzoylmethane', 't-ブチルメトキシジベンゾイルメタン', 'uv_filter_organic', 'Organic UV filter', ARRAY['sunscreens','makeup']::text[]),
(150, 'E — Japanese sunscreen launch coverage', 'Drometrizole Trisiloxane', 'drometrizole_trisiloxane', 'drometrizole-trisiloxane', 'Drometrizole Trisiloxane', 'ドロメトリゾールトリシロキサン', 'uv_filter_organic', 'Organic UV filter', ARRAY['sunscreens','makeup']::text[]);

-- Update any existing matching records first.
update public.beautydna_ingredient_intelligence i
set
  canonical_inci_name = s.canonical_inci_name,
  normalized_ingredient_name = s.normalized_ingredient_name,
  ingredient_slug = coalesce(i.ingredient_slug, s.ingredient_slug),
  preferred_display_name_en = coalesce(i.preferred_display_name_en, s.preferred_display_name_en),
  preferred_display_name_ja = coalesce(i.preferred_display_name_ja, s.japanese_labeling_name),
  japanese_labeling_name = coalesce(i.japanese_labeling_name, s.japanese_labeling_name),
  ingredient_family = coalesce(i.ingredient_family, s.ingredient_family),
  primary_function_summary = coalesce(i.primary_function_summary, s.primary_function_summary),
  common_product_types = case
    when coalesce(cardinality(i.common_product_types), 0) = 0 then s.common_product_types
    else i.common_product_types
  end,
  research_priority = s.priority_rank,
  coverage_tier = s.coverage_tier,
  schema_version = 'beauty-intelligence-ingredient-v1',
  record_status = coalesce(i.record_status, 'active'),
  review_status = coalesce(i.review_status, 'needs_review'),
  customer_usable = case when i.review_status = 'approved' then i.customer_usable else false end,
  updated_at = now()
from tmp_beautydna_core_150 s
where i.normalized_ingredient_name = s.normalized_ingredient_name
   or lower(i.canonical_inci_name) = lower(s.canonical_inci_name);

-- Insert only records that do not exist.
insert into public.beautydna_ingredient_intelligence (
  canonical_inci_name,
  normalized_ingredient_name,
  ingredient_slug,
  preferred_display_name_en,
  preferred_display_name_ja,
  japanese_labeling_name,
  ingredient_family,
  primary_function_summary,
  common_product_types,
  research_priority,
  coverage_tier,
  schema_version,
  record_status,
  review_status,
  customer_usable,
  current_version,
  created_at,
  updated_at
)
select
  s.canonical_inci_name,
  s.normalized_ingredient_name,
  s.ingredient_slug,
  s.preferred_display_name_en,
  s.japanese_labeling_name,
  s.japanese_labeling_name,
  s.ingredient_family,
  s.primary_function_summary,
  s.common_product_types,
  s.priority_rank,
  s.coverage_tier,
  'beauty-intelligence-ingredient-v1',
  'active',
  'needs_review',
  false,
  1,
  now(),
  now()
from tmp_beautydna_core_150 s
where not exists (
  select 1
  from public.beautydna_ingredient_intelligence i
  where i.normalized_ingredient_name = s.normalized_ingredient_name
     or lower(i.canonical_inci_name) = lower(s.canonical_inci_name)
);

create temporary table tmp_beautydna_aliases (
  ingredient_normalized_name text,
  alias_name text,
  normalized_alias_name text,
  language_code text,
  alias_type text,
  is_official boolean,
  is_ambiguous boolean,
  refers_to_scope text
) on commit drop;

insert into tmp_beautydna_aliases values
('water', '水', '水', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('water', 'Aqua', 'aqua', 'en', 'inci_synonym', FALSE, FALSE, 'exact_substance'),
('glycerin', 'グリセリン', 'グリセリン', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('butylene_glycol', 'BG', 'BG', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('butylene_glycol', '1,3-Butylene Glycol', '1_3_butylene_glycol', 'en', 'inci_synonym', FALSE, FALSE, 'exact_substance'),
('butylene_glycol', 'BG', 'bg', 'en', 'inci_synonym', FALSE, FALSE, 'exact_substance'),
('dipropylene_glycol', 'DPG', 'DPG', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('dipropylene_glycol', 'DPG', 'dpg', 'en', 'inci_synonym', FALSE, FALSE, 'exact_substance'),
('ethanol', 'エタノール', 'エタノール', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('ethanol', 'Alcohol', 'alcohol', 'en', 'inci_synonym', FALSE, FALSE, 'exact_substance'),
('ethanol', 'Alcohol Denat. (not always equivalent)', 'alcohol_denat_not_always_equivalent', 'en', 'inci_synonym', FALSE, FALSE, 'exact_substance'),
('propanediol', 'プロパンジオール', 'プロパンジオール', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('pentylene_glycol', 'ペンチレングリコール', 'ペンチレングリコール', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('1_2_hexanediol', '1,2-ヘキサンジオール', '1,2-ヘキサンジオール', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('diglycerin', 'ジグリセリン', 'ジグリセリン', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('sorbitol', 'ソルビトール', 'ソルビトール', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('betaine', 'ベタイン', 'ベタイン', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('methyl_gluceth_10', 'メチルグルセス-10', 'メチルグルセス-10', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('sodium_pca', 'PCA-Na', 'PCA-Na', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('sodium_pca', 'PCA Sodium', 'pca_sodium', 'en', 'inci_synonym', FALSE, FALSE, 'exact_substance'),
('trehalose', 'トレハロース', 'トレハロース', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('urea', '尿素', '尿素', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('sodium_lactate', '乳酸Na', '乳酸Na', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('arginine', 'アルギニン', 'アルギニン', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('citric_acid', 'クエン酸', 'クエン酸', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('sodium_citrate', 'クエン酸Na', 'クエン酸Na', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('lactic_acid', '乳酸', '乳酸', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('potassium_hydroxide', '水酸化K', '水酸化K', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('sodium_hydroxide', '水酸化Na', '水酸化Na', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('tromethamine', 'トロメタミン', 'トロメタミン', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('disodium_edta', 'EDTA-2Na', 'EDTA-2Na', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('disodium_edta', 'EDTA-2Na', 'edta_2na', 'en', 'inci_synonym', FALSE, FALSE, 'exact_substance'),
('phenoxyethanol', 'フェノキシエタノール', 'フェノキシエタノール', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('methylparaben', 'メチルパラベン', 'メチルパラベン', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('propylparaben', 'プロピルパラベン', 'プロピルパラベン', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('sodium_benzoate', '安息香酸Na', '安息香酸Na', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('potassium_sorbate', 'ソルビン酸K', 'ソルビン酸K', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('chlorphenesin', 'クロルフェネシン', 'クロルフェネシン', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('benzyl_alcohol', 'ベンジルアルコール', 'ベンジルアルコール', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('ethylhexylglycerin', 'エチルヘキシルグリセリン', 'エチルヘキシルグリセリン', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('caprylyl_glycol', 'カプリリルグリコール', 'カプリリルグリコール', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('fragrance', '香料', '香料', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('fragrance', 'Parfum', 'parfum', 'en', 'inci_synonym', FALSE, FALSE, 'exact_substance'),
('fragrance', 'Aroma', 'aroma', 'en', 'inci_synonym', FALSE, FALSE, 'exact_substance'),
('tocopherol', 'トコフェロール', 'トコフェロール', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('bht', 'BHT', 'BHT', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('sodium_metabisulfite', 'ピロ亜硫酸Na', 'ピロ亜硫酸Na', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('dehydroacetic_acid', 'デヒドロ酢酸', 'デヒドロ酢酸', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('sodium_phytate', 'フィチン酸Na', 'フィチン酸Na', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('phytic_acid', 'フィチン酸', 'フィチン酸', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('carbomer', 'カルボマー', 'カルボマー', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('xanthan_gum', 'キサンタンガム', 'キサンタンガム', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('hydroxyethylcellulose', 'ヒドロキシエチルセルロース', 'ヒドロキシエチルセルロース', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('cellulose_gum', 'セルロースガム', 'セルロースガム', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('sodium_polyacrylate', 'ポリアクリル酸Na', 'ポリアクリル酸Na', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('acrylates_c10_30_alkyl_acrylate_crosspolymer', '（アクリレーツ／アクリル酸アルキル（C10-30））クロスポリマー', '（アクリレーツ／アクリル酸アルキル（C10-30））クロスポリマー', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('ammonium_acryloyldimethyltaurate_vp_copolymer', '（アクリロイルジメチルタウリンアンモニウム／VP）コポリマー', '（アクリロイルジメチルタウリンアンモニウム／VP）コポリマー', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('polyacrylate_crosspolymer_6', 'ポリアクリレートクロスポリマー-6', 'ポリアクリレートクロスポリマー-6', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('polyacrylamide', 'ポリアクリルアミド', 'ポリアクリルアミド', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('c13_14_isoparaffin', 'C13-14イソパラフィン', 'C13-14イソパラフィン', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('laureth_7', 'ラウレス-7', 'ラウレス-7', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('silica', 'シリカ', 'シリカ', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('dimethicone', 'ジメチコン', 'ジメチコン', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('cyclopentasiloxane', 'シクロペンタシロキサン', 'シクロペンタシロキサン', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('phenyl_trimethicone', 'フェニルトリメチコン', 'フェニルトリメチコン', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('dimethicone_vinyl_dimethicone_crosspolymer', '（ジメチコン／ビニルジメチコン）クロスポリマー', '（ジメチコン／ビニルジメチコン）クロスポリマー', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('trimethylsiloxysilicate', 'トリメチルシロキシケイ酸', 'トリメチルシロキシケイ酸', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('peg_10_dimethicone', 'PEG-10ジメチコン', 'PEG-10ジメチコン', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('hydrogen_dimethicone', 'ハイドロゲンジメチコン', 'ハイドロゲンジメチコン', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('squalane', 'スクワラン', 'スクワラン', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('mineral_oil', 'ミネラルオイル', 'ミネラルオイル', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('mineral_oil', 'Paraffinum Liquidum', 'paraffinum_liquidum', 'en', 'inci_synonym', FALSE, FALSE, 'exact_substance'),
('petrolatum', 'ワセリン', 'ワセリン', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('petrolatum', 'White Petrolatum', 'white_petrolatum', 'en', 'inci_synonym', FALSE, FALSE, 'exact_substance'),
('petrolatum', 'Vaseline', 'vaseline', 'en', 'inci_synonym', FALSE, FALSE, 'exact_substance'),
('caprylic_capric_triglyceride', 'トリ（カプリル酸／カプリン酸）グリセリル', 'トリ（カプリル酸／カプリン酸）グリセリル', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('triethylhexanoin', 'トリエチルヘキサノイン', 'トリエチルヘキサノイン', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('cetyl_ethylhexanoate', 'エチルヘキサン酸セチル', 'エチルヘキサン酸セチル', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('ethylhexyl_palmitate', 'パルミチン酸エチルヘキシル', 'パルミチン酸エチルヘキシル', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('isononyl_isononanoate', 'イソノナン酸イソノニル', 'イソノナン酸イソノニル', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('dicaprylyl_carbonate', '炭酸ジカプリリル', '炭酸ジカプリリル', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('c12_15_alkyl_benzoate', '安息香酸アルキル（C12-15）', '安息香酸アルキル（C12-15）', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('isododecane', 'イソドデカン', 'イソドデカン', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('hydrogenated_polyisobutene', '水添ポリイソブテン', '水添ポリイソブテン', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('simmondsia_chinensis_jojoba_seed_oil', 'ホホバ種子油', 'ホホバ種子油', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('simmondsia_chinensis_jojoba_seed_oil', 'Jojoba Oil', 'jojoba_oil', 'en', 'inci_synonym', FALSE, FALSE, 'exact_substance'),
('camellia_japonica_seed_oil', 'ツバキ種子油', 'ツバキ種子油', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('oryza_sativa_rice_bran_oil', 'コメヌカ油', 'コメヌカ油', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('oryza_sativa_rice_bran_oil', 'Rice Bran Oil', 'rice_bran_oil', 'en', 'inci_synonym', FALSE, FALSE, 'exact_substance'),
('olea_europaea_olive_fruit_oil', 'オリーブ果実油', 'オリーブ果実油', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('butyrospermum_parkii_shea_butter', 'シア脂', 'シア脂', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('butyrospermum_parkii_shea_butter', 'Shea Butter', 'shea_butter', 'en', 'inci_synonym', FALSE, FALSE, 'exact_substance'),
('cetyl_alcohol', 'セタノール', 'セタノール', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('stearyl_alcohol', 'ステアリルアルコール', 'ステアリルアルコール', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('behenyl_alcohol', 'ベヘニルアルコール', 'ベヘニルアルコール', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('cetearyl_alcohol', 'セテアリルアルコール', 'セテアリルアルコール', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('stearic_acid', 'ステアリン酸', 'ステアリン酸', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('palmitic_acid', 'パルミチン酸', 'パルミチン酸', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('myristic_acid', 'ミリスチン酸', 'ミリスチン酸', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('lauric_acid', 'ラウリン酸', 'ラウリン酸', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('oleic_acid', 'オレイン酸', 'オレイン酸', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('glyceryl_stearate', 'ステアリン酸グリセリル', 'ステアリン酸グリセリル', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('peg_100_stearate', 'ステアリン酸PEG-100', 'ステアリン酸PEG-100', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('sorbitan_stearate', 'ステアリン酸ソルビタン', 'ステアリン酸ソルビタン', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('sucrose_stearate', 'ステアリン酸スクロース', 'ステアリン酸スクロース', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('hydrogenated_lecithin', '水添レシチン', '水添レシチン', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('lecithin', 'レシチン', 'レシチン', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('peg_60_hydrogenated_castor_oil', 'PEG-60水添ヒマシ油', 'PEG-60水添ヒマシ油', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('peg_40_hydrogenated_castor_oil', 'PEG-40水添ヒマシ油', 'PEG-40水添ヒマシ油', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('polysorbate_20', 'ポリソルベート20', 'ポリソルベート20', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('polysorbate_60', 'ポリソルベート60', 'ポリソルベート60', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('polysorbate_80', 'ポリソルベート80', 'ポリソルベート80', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('polyglyceryl_10_laurate', 'ラウリン酸ポリグリセリル-10', 'ラウリン酸ポリグリセリル-10', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('polyglyceryl_10_myristate', 'ミリスチン酸ポリグリセリル-10', 'ミリスチン酸ポリグリセリル-10', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('polyglyceryl_2_diisostearate', 'ジイソステアリン酸ポリグリセリル-2', 'ジイソステアリン酸ポリグリセリル-2', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('glyceryl_caprylate', 'カプリル酸グリセリル', 'カプリル酸グリセリル', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('sorbitan_oleate', 'オレイン酸ソルビタン', 'オレイン酸ソルビタン', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('aluminum_hydroxide', '水酸化Al', '水酸化Al', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('sodium_cocoyl_glycinate', 'ココイルグリシンNa', 'ココイルグリシンNa', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('potassium_cocoyl_glycinate', 'ココイルグリシンK', 'ココイルグリシンK', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('sodium_cocoyl_glutamate', 'ココイルグルタミン酸Na', 'ココイルグルタミン酸Na', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('disodium_cocoyl_glutamate', 'ココイルグルタミン酸2Na', 'ココイルグルタミン酸2Na', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('sodium_lauroyl_glutamate', 'ラウロイルグルタミン酸Na', 'ラウロイルグルタミン酸Na', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('sodium_methyl_cocoyl_taurate', 'ココイルメチルタウリンNa', 'ココイルメチルタウリンNa', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('sodium_lauroyl_methyl_taurate', 'ラウロイルメチルタウリンNa', 'ラウロイルメチルタウリンNa', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('sodium_lauroyl_methylaminopropionate', 'ラウロイルメチルアラニンNa', 'ラウロイルメチルアラニンNa', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('cocamidopropyl_betaine', 'コカミドプロピルベタイン', 'コカミドプロピルベタイン', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('lauryl_betaine', 'ラウリルベタイン', 'ラウリルベタイン', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('sodium_cocoyl_isethionate', 'ココイルイセチオン酸Na', 'ココイルイセチオン酸Na', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('sodium_laureth_sulfate', 'ラウレス硫酸Na', 'ラウレス硫酸Na', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('decyl_glucoside', 'デシルグルコシド', 'デシルグルコシド', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('coco_glucoside', 'ココイルグルコシド', 'ココイルグルコシド', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('potassium_myristate', 'ミリスチン酸K', 'ミリスチン酸K', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('potassium_stearate', 'ステアリン酸K', 'ステアリン酸K', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('potassium_palmitate', 'パルミチン酸K', 'パルミチン酸K', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('potassium_laurate', 'ラウリン酸K', 'ラウリン酸K', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('peg_7_glyceryl_cocoate', 'ヤシ油脂肪酸PEG-7グリセリル', 'ヤシ油脂肪酸PEG-7グリセリル', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('sodium_hyaluronate', 'ヒアルロン酸Na', 'ヒアルロン酸Na', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('sodium_hyaluronate', 'Hyaluronic Acid Sodium Salt', 'hyaluronic_acid_sodium_salt', 'en', 'inci_synonym', FALSE, FALSE, 'exact_substance'),
('hydrolyzed_hyaluronic_acid', '加水分解ヒアルロン酸', '加水分解ヒアルロン酸', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('sodium_acetylated_hyaluronate', 'アセチルヒアルロン酸Na', 'アセチルヒアルロン酸Na', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('niacinamide', 'ナイアシンアミド', 'ナイアシンアミド', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('ascorbic_acid', 'アスコルビン酸', 'アスコルビン酸', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('ascorbyl_glucoside', 'アスコルビルグルコシド', 'アスコルビルグルコシド', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('3_o_ethyl_ascorbic_acid', '3-O-エチルアスコルビン酸', '3-O-エチルアスコルビン酸', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('tocopheryl_acetate', '酢酸トコフェロール', '酢酸トコフェロール', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('tranexamic_acid', 'トラネキサム酸', 'トラネキサム酸', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('dipotassium_glycyrrhizate', 'グリチルリチン酸2K', 'グリチルリチン酸2K', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('dipotassium_glycyrrhizate', 'Glycyrrhizic Acid 2K', 'glycyrrhizic_acid_2k', 'en', 'inci_synonym', FALSE, FALSE, 'exact_substance'),
('dipotassium_glycyrrhizate', 'Dipotassium Glycyrrhizinate', 'dipotassium_glycyrrhizinate', 'en', 'inci_synonym', FALSE, FALSE, 'exact_substance'),
('stearyl_glycyrrhetinate', 'グリチルレチン酸ステアリル', 'グリチルレチン酸ステアリル', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('allantoin', 'アラントイン', 'アラントイン', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('panthenol', 'パンテノール', 'パンテノール', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('arbutin', 'アルブチン', 'アルブチン', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('salicylic_acid', 'サリチル酸', 'サリチル酸', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('ceramide_np', 'セラミドNP', 'セラミドNP', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('hydrolyzed_collagen', '加水分解コラーゲン', '加水分解コラーゲン', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('camellia_sinensis_leaf_extract', 'チャ葉エキス', 'チャ葉エキス', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('coix_lacryma_jobi_ma_yuen_seed_extract', 'ハトムギ種子エキス', 'ハトムギ種子エキス', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('zinc_oxide', '酸化亜鉛', '酸化亜鉛', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('titanium_dioxide', '酸化チタン', '酸化チタン', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('ethylhexyl_methoxycinnamate', 'メトキシケイヒ酸エチルヘキシル', 'メトキシケイヒ酸エチルヘキシル', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('ethylhexyl_methoxycinnamate', 'Octinoxate', 'octinoxate', 'en', 'inci_synonym', FALSE, FALSE, 'exact_substance'),
('ethylhexyl_triazone', 'エチルヘキシルトリアゾン', 'エチルヘキシルトリアゾン', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('diethylamino_hydroxybenzoyl_hexyl_benzoate', 'ジエチルアミノヒドロキシベンゾイル安息香酸ヘキシル', 'ジエチルアミノヒドロキシベンゾイル安息香酸ヘキシル', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('diethylamino_hydroxybenzoyl_hexyl_benzoate', 'Uvinul A Plus', 'uvinul_a_plus', 'en', 'inci_synonym', FALSE, FALSE, 'exact_substance'),
('bis_ethylhexyloxyphenol_methoxyphenyl_triazine', 'ビスエチルヘキシルオキシフェノールメトキシフェニルトリアジン', 'ビスエチルヘキシルオキシフェノールメトキシフェニルトリアジン', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('bis_ethylhexyloxyphenol_methoxyphenyl_triazine', 'Tinosorb S', 'tinosorb_s', 'en', 'inci_synonym', FALSE, FALSE, 'exact_substance'),
('octocrylene', 'オクトクリレン', 'オクトクリレン', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('polysilicone_15', 'ポリシリコーン-15', 'ポリシリコーン-15', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('butyl_methoxydibenzoylmethane', 't-ブチルメトキシジベンゾイルメタン', 't-ブチルメトキシジベンゾイルメタン', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('butyl_methoxydibenzoylmethane', 'Avobenzone', 'avobenzone', 'en', 'inci_synonym', FALSE, FALSE, 'exact_substance'),
('drometrizole_trisiloxane', 'ドロメトリゾールトリシロキサン', 'ドロメトリゾールトリシロキサン', 'ja', 'japanese_label_name', TRUE, FALSE, 'exact_substance'),
('drometrizole_trisiloxane', 'Mexoryl XL', 'mexoryl_xl', 'en', 'inci_synonym', FALSE, FALSE, 'exact_substance');

insert into public.beautydna_ingredient_aliases (
  ingredient_id,
  alias_name,
  normalized_alias_name,
  language_code,
  alias_type,
  is_official,
  is_ambiguous,
  refers_to_scope,
  review_status,
  created_at,
  updated_at
)
select
  i.id,
  a.alias_name,
  a.normalized_alias_name,
  a.language_code,
  a.alias_type,
  a.is_official,
  a.is_ambiguous,
  a.refers_to_scope,
  'needs_review',
  now(),
  now()
from tmp_beautydna_aliases a
join public.beautydna_ingredient_intelligence i
  on i.normalized_ingredient_name = a.ingredient_normalized_name
where not exists (
  select 1
  from public.beautydna_ingredient_aliases e
  where e.ingredient_id = i.id
    and lower(e.alias_name) = lower(a.alias_name)
);

commit;
